// Code generated by aocgen; DO NOT EDIT.
package year2023

type Day02 struct{}

func (p Day02) PartA(lines []string) any {
	return "implement_me"
}

func (p Day02) PartB(lines []string) any {
	return "implement_me"
}
